### ISSUE TITLE
Crashing on startup (Windows Server 2022 with desktop experience and .NET 6 desktop runtime)

### ISSUE THREAD

**Issue by mamift** [ErikEJ/SqlQueryStress#158]
So i've downloaded this release: https://github.com/ErikEJ/SqlQueryStress/releases/tag/0.9.7.164

And it's crashing on startup. I am running it on a Windows Server 2022 host (it has .NET 6 desktop runtime installed and also the Desktop Experience [so it's not running Windows Server core]).

Is Windows Server not supported perhaps? I can't see a 'system requirements' list anywhere in this repo.

This is the first error that get's logged:
```
Application: SqlQueryStress.exe
CoreCLR Version: 6.0.3024.21525
.NET Version: 6.0.30
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException: Object reference not set to an instance of an object.
   at SQLQueryStress.SqlControl.SqlControl_OnLoaded(Object sender, RoutedEventArgs e)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.Resize(ICompositionTarget resizedCompositionTarget)
   at System.Windows.Interop.HwndTarget.OnResize()
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
```

This is the second event log:

```
Faulting application name: SqlQueryStress.exe, version: 0.9.7.164, time stamp: 0x661e012c
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x00007ff5d1813e13
Faulting process id: 0x2530
Faulting application start time: 0x01dab7be4b1a2d69
Faulting application path: C:\Downloads\SqlQueryStress.exe
Faulting module path: unknown
Report Id: 345f6d83-22c0-4101-8dfa-1ae8645af7e4
Faulting package full name: 
Faulting package-relative application ID: 
```

Finally (and strangely a third one gets logged 5 minutes later):

```
Faulting application name: SqlQueryStress.exe, version: 0.9.7.164, time stamp: 0x661e012c
Faulting module name: KERNELBASE.dll, version: 10.0.20348.2461, time stamp: 0x6008e061
Exception code: 0xc000041d
Fault offset: 0x000000000003f19c
Faulting process id: 0x2530
Faulting application start time: 0x01dab7be4b1a2d69
Faulting application path: C:\Downloads\SqlQueryStress.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: db8bfd26-e84e-4779-903b-653c5a0f1c54
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by ErikEJ** [comment]
@mamift Thanks for reporting, the latest release is broken, I am working on a fix
