### ISSUE TITLE
sqlstresscmd connection issue linux

### ISSUE THREAD

**Issue by viblo-majority** [ErikEJ/SqlQueryStress#168]
Im trying to run sqlstresscmd from a linux server, but it fails when connecting. The same settings file works locally when running sqlstresscmd on my Windows 11 laptop.

The connection part of the config looks like this (but with real values for db, login and server):
```
    "MainDbConnectionInfo": {
        "AdditionalParameters": "",
        "ApplicationIntent": 0,
        "AzureMFA": true,
        "ConnectTimeout": 15,
        "Database": "[DBNAME]",
        "EnablePooling": true,
        "EncryptOption": "False",
        "IntegratedAuth": false,
        "Login": "[MY EMAIL]",
        "MaxPoolSize": 2,
        "Password": "",
        "Server": "[SERVER NAME].database.windows.net",
        "TrustServerCertificate": false
    },
```

Is this supposed to work on Linux from the command line?

Ps. Thanks for SQLStress, very handy when something needs benchmarking!

**Comment by ErikEJ** [comment]
"Fails" ??? Please provide the exact and full error message.

**Comment by viblo-majority** [comment]
Sorry, missed the most important part: It says `Invalid connection info` and nothing more.

**Comment by ErikEJ** [comment]
Let me try to push a new version to NuGet, the current one is a bit old.

**Comment by ErikEJ** [comment]
@viblo-majority New version of the tool just published

**Comment by viblo-majority** [comment]
Same issue (from Ubuntu in WSL):
```
vb@vibl:~$ dotnet tool update -g sqlstresscmd
Skipping NuGet package signature verification.
Tool 'sqlstresscmd' was successfully updated from version '0.9.18' to version '0.9.19'.
vb@vibl:~$ sqlstresscmd -s sqlstress.json
Invalid connection info
```

**Comment by ErikEJ** [comment]
@viblo-majority I just pushed a new version (0.9.20) that actually logs the failure to connect!

**Comment by viblo-majority** [comment]
Ah, then I get this output:
```
Failed to connect to server: Microsoft.Data.SqlClient.SqlException (0x80131904): Failed to authenticate the user  in Active Directory (Authentication=ActiveDirectoryInteractive).
Error code 0xlinux_xdg_open_failed
Unable to open a web page using xdg-open, gnome-open, kfmclient or wslview tools. See inner exception for details. Possible causes for this error are: tools are not installed or they cannot open a URL. Make sure you can open a web page by invoking from a terminal: xdg-open https://www.bing.com
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.GetFedAuthToken(SqlFedAuthInfo fedAuthInfo)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.OnFedAuthInfo(SqlFedAuthInfo fedAuthInfo)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.TdsParser.Run(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.CompleteLogin(Boolean enlistOK)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.AttemptOneLogin(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, TimeoutTimer timeout, Boolean withFailover)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString connectionOptions, SqlCredential credential, TimeoutTimer timeout)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutTimer timeout, SqlConnectionString connectionOptions, SqlCredential credential, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken, DbConnectionPool pool, Func`3 accessTokenCallback)
   at Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry, SqlConnectionOverrides overrides)
   at Microsoft.Data.SqlClient.SqlConnection.Open(SqlConnectionOverrides overrides)
   at SQLQueryStress.ConnectionInfo.TestConnection() in C:\projects\sqlquerystress\src\SQLQueryStress\ConnectionInfo.cs:line 189
ClientConnectionId:5582c437-9ebd-4521-a2b0-8a44aaca0932
Invalid connection info
```

**Comment by ErikEJ** [comment]
@viblo-majority Amazing! So you are good to go now ?? - thanks for your help with the UX improvement

**Comment by viblo-majority** [comment]
@ErikEJ Unfortunately it doesnt cover my original use case. 
I want to connect from a linux VM (physically) close to the the database. The DB instance runs in the US, but Im in Europe. To avoid the latency I can connect with SSH or through K8s to a server in US. 

I was out of time to try more yesterday, but did some unsuccessful tries today. I guess this is something with the DB Auth libraries sqlstresscmd uses and how the interactive auth works which might not be easy to work around. 

I understand if you think its out of scope for sqlstresscmd. But I still write up what I tried here in case you (or someone else) spots what I did wrong or want to troubleshoot:

This is what I tired (from a docker container):
1. I replaced `xdg-open` with this little bash script and put on the path, to simulate a browser:
```
#!/bin/bash
echo "$@" > ~/browser.url
sleep 20
true
```
2. Run sqlstresscmd in one terminal window
3. In another terminal window, open `~/browser.url`, copy the url and open in my local browser, and do the auth
4. Copy the resulting url that the browser redirects to when done (pointing to a localhost address)
5. in the other terminal window, curl the url. The returned html shows "Authentication complete. You can return to the application. Feel free to close this browser tab." so this seems to work.
6. Wait until sqlstresscmd understands auth is completed....
Unfortunately `sqlstresscmd` waits and waits until there's a timeout, with this exception

```
Failed to connect to server: Microsoft.Data.SqlClient.SqlException (0x80131904): Active Directory Interactive authentication timed out. The user took too long to respond to the authentication request.
 ---> System.TimeoutException: Active Directory Interactive authentication timed out. The user took too long to respond to the authentication request.
   at Microsoft.Data.SqlClient.ActiveDirectoryAuthenticationProvider.AcquireTokenInteractiveDeviceFlowAsync(IPublicClientApplication app, String[] scopes, Guid connectionId, String userId, SqlAuthenticationMethod authenticationMethod, CancellationTokenSource cts, ICustomWebUi customWebUI, Func`2 deviceCodeFlowCallback)
   at Microsoft.Data.SqlClient.ActiveDirectoryAuthenticationProvider.AcquireTokenAsync(SqlAuthenticationParameters parameters)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.<>c__DisplayClass148_1.<<GetFedAuthToken>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.GetFedAuthToken(SqlFedAuthInfo fedAuthInfo)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.GetFedAuthToken(SqlFedAuthInfo fedAuthInfo)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.OnFedAuthInfo(SqlFedAuthInfo fedAuthInfo)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.TdsParser.Run(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.CompleteLogin(Boolean enlistOK)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.AttemptOneLogin(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, TimeoutTimer timeout, Boolean withFailover)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString connectionOptions, SqlCredential credential, TimeoutTimer timeout)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutTimer timeout, SqlConnectionString connectionOptions, SqlCredential credential, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken, DbConnectionPool pool, Func`3 accessTokenCallback)
   at Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry, SqlConnectionOverrides overrides)
   at Microsoft.Data.SqlClient.SqlConnection.Open(SqlConnectionOverrides overrides)
   at SQLQueryStress.ConnectionInfo.TestConnection() in C:\projects\sqlquerystress\src\SQLQueryStress\ConnectionInfo.cs:line 189
ClientConnectionId:0402200a-3f5b-46c6-af9c-e8c0ef3eaab4
Invalid connection info
```

**Comment by ErikEJ** [comment]
@viblo-majority I doubt your use case is valid, but you can ask in the SqlClient repo perhaps?
