### ISSUE TITLE
Exception: Value is not valid for 'Value'. 'Value' should be between 'minimum' and 'maximum'.

### ISSUE THREAD

**Issue by Oleg26Dev** [ErikEJ/SqlQueryStress#46]
I receive this kind of uncatching exception when I run many iterations
-----------------------------

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentOutOfRangeException: Value of '142' is not valid for 'Value'. 'Value' should be between 'minimum' and 'maximum'.
Parameter name: Value
   at System.Windows.Forms.ProgressBar.set_Value(Int32 value)
   at SQLQueryStress.Form1.UpdateUi() in D:\_Samples\SQLServer\SqlQueryStress-master\src\SQLQueryStress\Form1.cs:line 414
   at SQLQueryStress.Form1.mainUITimer_Tick(Object sender, EventArgs e) in D:\_Samples\SQLServer\SqlQueryStress-master\src\SQLQueryStress\Form1.cs:line 283
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

...
************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by Oleg26Dev** [comment]
Oh, sorry, it may be I have the old version.

**Comment by ErikEJ** [comment]
Could you try the latest build? I believe it is fixed.

**Comment by Oleg26Dev** [comment]
Yes, now I am working with the latest build. It seems it was fixed, there is Min:

 progressBar1.Value = Math.Min((int) (_totalIterations / (decimal) _totalExpectedIterations * 100), 100);

**Comment by ErikEJ** [comment]
Great!
